```{r chapter-5-setup, cache = FALSE, echo = FALSE, message = FALSE, warning = FALSE}

library(data.table)
library(tidyverse)
library(hrbrthemes)
library(lindia)
library(finalfit)
library(sigr)
library(papaja)
library(here)
library(kableExtra)
library(GGally)
library(gtools)
library(MASS)
library(corrplot)
library(magrittr)
library(caret)
library(factoextra)
library(broom)
library(ggord)
library(skimr)
library(sjstats)
library(explor)
library(stargazer)
# For overriding MASS select() 
select <- dplyr::select
set.seed(2018)
```


# Week 6 – Analysis of longitudinal data


```{r chapter-8-generic-instruction, echo = FALSE}
# Implement the analyses of Chapter 8 of MABS using the RATS data. (0-7 points)
```


## Analyses of the MABS chapter 8 using the RATS data

```{r chapter6-load-data-rats, cache = TRUE, echo = FALSE, message=FALSE, warning = FALSE}

rats <- fread(here("data/rats.csv"))
rats_raw <- fread(here("data/rats.txt"))
rats_raw <- rats_raw[,2:dim(rats_raw)[2]]

rats %<>% mutate(
  id = factor(id),
  group = factor(group),
  weeks = factor(weeks)
)


```

```{r rats-overview, echo = FALSE, cache = TRUE}
skim(rats)
```


### Figure 8.1

```{r rats-81, echo = FALSE, cache = TRUE}
ggplot(rats, aes(x = time, y = rats, linetype = id)) + 
  geom_line() + scale_linetype_manual(values = rep(1:10, times=4)) + 
  facet_grid(. ~ group, labeller = label_both) +
  theme_minimal() + theme(legend.position = "none") +
  theme(panel.grid.minor.y = element_blank()) +
  scale_y_continuous(
    limits = c(min(rats$rats), max(rats$rats)),
    name = "weight (g)") +
  scale_x_discrete(name = "time (days)")


```

### Figure 8.2

Previous figure but with standardized measurement values.

```{r rats-82, echo=FALSE, cache = TRUE}
# Standardise the scores:
rats %<>%
  group_by(time) %>%
  mutate(stdrats = (rats - mean(rats))/sd(rats)) %>%
  ungroup()

ggplot(rats , aes(x = time, y = stdrats, linetype = id)) + 
  geom_line() + scale_linetype_manual(values = rep(1:10, times = 4)) +
  facet_grid(. ~ group, labeller = label_both) +
  theme_minimal() + theme(legend.position = "none") +
  theme(panel.grid.minor.y = element_blank()) +
  scale_y_continuous(name = "standardized weight") +
  scale_x_discrete(name = "time (days)")

```

### Figure 8.3

Change over time, with summary values.

```{r rats-83, echo=FALSE, cache = TRUE}
# Make a summary data:
n <- length(0:8) # weeks, incl. baseline (0)
rats_summary <- rats %>%
  group_by(group, time) %>%
  summarise(mean = mean(rats), se = sd(rats)/sqrt(n)) %>%
  ungroup()


ggplot(rats_summary, aes(x = time, y = mean, linetype = group, shape = group)) +
  geom_line() + scale_linetype_manual(values = c(1,2,3)) +
  geom_point(size = 3) + scale_shape_manual(values = c(1,2,3)) +
  geom_errorbar(aes(ymin=mean-se, ymax = mean+se, linetype = "1"), width=0.3) + 
  theme_minimal() + 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
    ) +
  theme(legend.position = c(0.8,0.8)) +
  scale_y_continuous(name = "mean(rats) +/- se(rats)") +
  scale_x_discrete(name = "time (days)")
```

### Figure 8.4

```{r rats-8-4, echo = FALSE, cache = TRUE}
ggplot(rats, aes(x = factor(time), y = rats, fill = group)) +
  geom_boxplot(position = position_dodge(width = 0.9)) +
  theme_minimal() + 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  theme(legend.position = c(0.8,0.8)) +
  scale_x_discrete(name = "time (days)")

```

### Figure 8.5


```{r rats-8-5, echo=FALSE, cache = TRUE}
# Make a summary data of the post treatment weeks (8<)
rats_post <- rats %>%
  filter(time > 1) %>%
  group_by(group, id) %>%
  summarise(mean=mean(rats)) %>%
  ungroup()
glimpse(rats_post)

ggplot(rats_post, aes(x = group, y = mean)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  geom_jitter(height = 0, width = 0.1, size = 0.7) + 
  theme_bw() + 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  stat_summary(
    fun.y = "mean",
    geom = "point",
    shape = 23,
    size = 3,
    fill = "red"
    ) +
  scale_y_continuous(name = "mean(rats), weeks 8<") +
  scale_x_discrete(name = "treatment group")

```

```{r add-baseline, echo = FALSE, cache = TRUE}
# It is best to add baseline now, before filtering
# Add the baseline from the original data as a new variable to the summary data:
baseline <- rats_raw$WD1
rats_post %<>%
  mutate(baseline)

```


### Figure 8.6

```{r rats-8-6, echo=FALSE, fig.width = 3, fig.height=4, cache = TRUE}
# Remove the outlier, case no 12 which has mean 594

rats_post %<>% filter(mean < 550)
glimpse(rats_post)
ggplot(rats_post, aes(x = group, y = mean)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  geom_jitter(height = 0, width = 0.1, size = 0.7) +
  theme_bw() + 
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
    ) +
  stat_summary(
    fun.y = "mean",
    geom = "point",
    shape = 23,
    size = 3,
    fill = "white"
    ) +
  scale_y_continuous(name = "mean(rats), weeks 8>") +
  scale_x_discrete(name = "time (days)")

```

### Table 8.3

```{r Table 8.3, echo=TRUE, cache = TRUE}
fit = lm(formula = mean ~ factor(group), data=rats_post)
anova(fit)
```

### Table 8.4

```{r Table 8.4, echo=TRUE, cache = TRUE}

# Fit the ANCOVA model and see the results:
fit <- lm(mean ~ baseline + factor(group), data = rats_post)
summary(fit)
anova(fit)
```

## Analyses of the MABS chapter 9 using the BPRS data

```{r chapter9-generic-instruction, echo = FALSE}
# Implement the analyses of Chapter 9 of MABS using the BPRS data. (0-8 points)
```

```{r chapter6-load-data-bprs, echo = FALSE, message=FALSE, warning=FALSE}

bprs <- fread(here("data/bprs.csv"))
bprs_raw <- fread(here("data/bprs.txt"))

bprs %<>% mutate(
  subject = as.factor(subject),
  treatment = as.factor(treatment),
  weeks = as.factor(weeks),
  week = as.factor(week)
)


```

```{r bprs-overview, echo = FALSE}
skim(bprs)
```

### Figure 9.1

```{r, echo = FALSE, fig.height=5, fig.width=5, cache = TRUE}
ggplot(bprs, aes(x = week, y = bprs, group=week)) +
  geom_violin(draw_quantiles = c(0.25, 0.5, 0.75)) +
  geom_jitter(height = 0, width = 0.1, size = 0.6) +
  scale_x_discrete(name = "Time (weeks)", breaks = seq(0, 8, 1)) +
  scale_y_continuous(name = "BPRS-score") +
  stat_summary(
    fun.y = "mean",
    geom = "point",
    shape = 23,
    size = 2,
    fill = "red"
    ) +
  theme_bw() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
    ) + 
  facet_grid(. ~ treatment, labeller = label_both)
```


```{r bprs-standardized, echo=FALSE, cache = TRUE}
# Standardise the scores:
bprs %<>%
  group_by(week) %>%
  mutate(stdbprs = (bprs - mean(bprs))/sd(bprs)) %>%
  ungroup()

ggplot(bprs , aes(x = week, y = stdbprs, group = subject)) + 
  geom_line(aes(linetype = subject)) + 
  theme_minimal() + theme(legend.position = "none") +
  theme(panel.grid.minor.y = element_blank()) +
  scale_y_continuous(name = "standardized bprs") +
  scale_x_discrete(name = "Time (weeks)", breaks = seq(0, 8, 1)) +
  facet_grid(. ~ treatment, labeller = label_both)

```



### Table 9.3

```{r, echo=TRUE}
bprs_lm <- lm(bprs ~ week + treatment, data = bprs)
summary(bprs_lm)
```

### Figure 9.2

```{r, echo=FALSE, cache = TRUE}
ggplot(bprs, aes(x = week, y = bprs, group = subject)) +
  geom_line(aes(linetype = subject)) +
  scale_x_discrete(name = "Time (weeks)", breaks = seq(0, 8, 1)) +
  scale_y_continuous(name = "BPRS-score") +
  theme_bw() + theme(legend.position = "none") +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  facet_grid(. ~ treatment, labeller = label_both)

```


### Figure 9.3

```{r, echo=FALSE, fig.width=10, fig.height=10, cache = TRUE}
pairs(bprs_raw[, 3:11], cex = 0.9, col=factor(bprs_raw$treatment))
```


### Table 9.4

```{r, echo=TRUE, message=FALSE, cache=TRUE, warning=FALSE}
library("lme4")
bprs_ref <- lmer(bprs ~ week + treatment + (1 | subject), data = bprs, REML = FALSE)
summary(bprs_ref)
```


### Table 9.5

```{r, echo=TRUE, warning = FALSE, message=FALSE}
library(lme4)
bprs_ref1 <- lmer(bprs ~ week + treatment + (week | subject), data = bprs, REML = FALSE)
summary(bprs_ref1)
anova(bprs_ref1, bprs_ref)
```

### Table 9.6

```{r, echo=TRUE, warning = FALSE}
bprs_ref2 <- lmer(bprs ~ week * treatment + (week | subject), data = bprs, REML = FALSE)
summary(bprs_ref2)
anova(bprs_ref1, bprs_ref2)
```

## Figure 9.4

```{r, echo=FALSE, fig.width=6, fig.height=4, eval = TRUE, cache = TRUE }
bprs_fitted <- fitted(bprs_ref2)
bprs %<>% mutate(bprs_fitted)

graph1 <- 
  ggplot(bprs, aes(x = week, y = bprs, group = subject)) +
  geom_line(aes(linetype = subject)) +
  scale_x_discrete(name = "Time (weeks)",breaks = seq(0, 8, 1)) +
  scale_y_continuous(name = "BPRS-score") +
  theme_bw() + theme(legend.position = "none") +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
    ) +
  ggtitle("Observed BPRS-scores") +
  facet_grid(. ~ treatment, labeller = label_both)



```

```{r, echo=FALSE, eval=TRUE, cache = TRUE, fig.width=6, fig.height=4}
graph2 <- 
  ggplot(bprs, aes(x = week, y = bprs_fitted, group = subject)) +
  geom_line(aes(linetype = subject)) +
  scale_x_discrete(name = "Time (weeks)",breaks = seq(0, 8, 1)) +
  scale_y_continuous(name = "BPRS-score") +
  theme_bw() + theme(legend.position = "none") +
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) +
  ggtitle("Fitted BPRS scores") +
  facet_grid(. ~ treatment, labeller = label_both)

```

```{r print-graphics, echo = FALSE}
graph1;graph2
```


